// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANwimx32-66J5sGH7NcetR0mnt7gkjSjo',
    appId: '1:619546907733:web:f251346f2f31ff710770dc',
    messagingSenderId: '619546907733',
    projectId: 'random-quotes-app-64e58',
    authDomain: 'random-quotes-app-64e58.firebaseapp.com',
    storageBucket: 'random-quotes-app-64e58.firebasestorage.app',
    measurementId: 'G-LEF23Y3TQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTxJC2KKqcj2Jp-AzJ2IjehbgpRhGdG_E',
    appId: '1:619546907733:android:429736dbf4e975e30770dc',
    messagingSenderId: '619546907733',
    projectId: 'random-quotes-app-64e58',
    storageBucket: 'random-quotes-app-64e58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcoaYCSS0M5YYNi0MGk2mRvtrAEt36Z0E',
    appId: '1:619546907733:ios:edac530836923a750770dc',
    messagingSenderId: '619546907733',
    projectId: 'random-quotes-app-64e58',
    storageBucket: 'random-quotes-app-64e58.firebasestorage.app',
    iosBundleId: 'com.example.randomquotesgeneratorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANwimx32-66J5sGH7NcetR0mnt7gkjSjo',
    appId: '1:619546907733:web:ca725b14ba31f4a30770dc',
    messagingSenderId: '619546907733',
    projectId: 'random-quotes-app-64e58',
    authDomain: 'random-quotes-app-64e58.firebaseapp.com',
    storageBucket: 'random-quotes-app-64e58.firebasestorage.app',
    measurementId: 'G-SSYL703XCL',
  );
}
